@echo off
setlocal EnableDelayedExpansion
color 17
cls
echo.
echo.
echo    ____        _      __    ___            ___      ____
echo   / __/_______(_)__  / /_  / _ )__ __  __ / (_)__  / / /
echo  _\ \/ __/ __/ / _ \/ __/ / _  / // / / // / (_- // / /
echo /___/\__/_/ /_/ .__/\__/ /____/\_, /  \___/_/__ /_ /_/
echo              /_/              /___/
echo.
echo.
echo Before proceeding, make sure to create a backup of your system.
echo This script will modify various settings. Continue only if you understand the changes.
echo.
set /p "continue=Press ENTER to start the process..."

powershell "Get-AppxPackage -Allusers *Microsoft.BingWeather* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Getstarted* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *OfficeHub* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.BioEnrollment* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftEdgeDevToolsClient* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Windows.ParentalControls* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxGameOverlay* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxSpeechToTextOverlay* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxIdentityProvider* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxGamingOverlay* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxApp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Xbox.TCUI* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.People* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.PeopleExperienceHost* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.SkypeApp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Windows.Photos* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsAlarms* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsCamera* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *microsoft.windowscommunicationsapps* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsMaps* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *WindowsPhone* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsSoundRecorder* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Xbox* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.ZuneVideo* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.StorePurchaseApp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *3DBuilder* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.YourPhone* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *StickyNotes* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *OneCalendar* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *OneConnect* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *ACG* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *CandyCrush* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Facebook* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Plex* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Spotify* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Twitter* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Viber* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *3d* | Remove-AppxPackage"
powershell "Get-AppxPackage -AllUsers *Reader* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsFeedbackHub* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.GetHelp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MixedReality.Portal* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Wallet* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Windows.NarratorQuickStart* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.XboxGameCallableUI* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Todos* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *OneDrive* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Microsoft3DViewer* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Windows.CallingShellApp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.549981C3F5F10* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Minecraft* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftEdge* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftEdge.Stable* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *sway* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *holographic* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Office.OneNote* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *WebExperience* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.ScreenSketch* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *PowerAutomateDesktop* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Appconnector* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *CommsPhone* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *ConnectivityStore* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Messaging* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *MicrosoftPowerBIForWindows* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *NetworkSpeedTest* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Print3D* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Whiteboard* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *WindowsReadingList* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Clipchamp.Clipchamp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *MicrosoftWindows.Client.WebExperience* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Windows.CBSPreview* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *MicrosoftTeams* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsFeedback* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Windows.ContactSupport* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WindowsStore* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *SpotifyMusic* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.ZuneVideo* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *ACGMediaPlayer* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *ActiproSoftwareLLC* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *AdobePhotoshopExpress* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Amazon.com.Amazon* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Asphalt8Airborne* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *AutodeskSketchBook* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *BubbleWitch3Saga* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *CaesarsSlotsFreeCasino* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *COOKINGFEVER* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *CyberLinkMediaSuiteEssentials* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *DisneyMagicKingdoms* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Disney* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Dolby* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *DrawboardPDF* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Duolingo-LearnLanguagesforFree* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *EclipseManager* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *FarmVille2CountryEscape* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *FitbitCoach* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Flipboard* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *HiddenCity* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Hulu* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *iHeartRadio* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Keeper* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *LinkedInforWindows* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *MarchofEmpires* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Netflix* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *NYTCrossword* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *PandoraMediaInc* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *PhototasticCollage* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *PicsArt-PhotoStudio* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Plex* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *PolarrPhotoEditorAcademicEdition* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *RoyalRevolt* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Shazam* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Sidia.LiveWallpaper* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *SlingTV* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Speed Test* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *TuneInRadio* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *WinZipUniversal* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Wunderlist* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *XING* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *SAMSUNGELECTRONICSCO* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Advertising.Xaml* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.PrintDialog* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WebpImageExtension* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.WebMediaExtensions* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.VP9VideoExtensions* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.HEIFImageExtension* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Windows.CBSPreview* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.Windows.ContentDeliveryManager* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.BingNews* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.GamingApp* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.ZuneMusic* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *Microsoft.OneDrive* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *MicrosoftCorporationII.QuickAssist* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *SpotifyAB.SpotifyMusic* | Remove-AppxPackage"
powershell "Get-AppxPackage -Allusers *WebExperience* | Remove-AppxPackage"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.ScreenSketch* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MicrosoftStickyNotes* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.GetHelp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsFeedbackHub* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *MicrosoftWindows.Client.WebExperience* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.YourPhone* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxGameOverlay* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.BingWeather* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Getstarted* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Microsoft3DViewer* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MicrosoftEdge.Stable* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MicrosoftOfficeHub* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.549981C3F5F10* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MicrosoftStickyNotes* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MixedReality.Portal* | Remove-AppxProvisionedPackage -online"
:: powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.MSPaint* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Office.OneNote* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.People* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.StorePurchaseApp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.SkypeApp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Wallet* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Windows.Photos* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsAlarms* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsCamera* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *microsoft.windowscommunicationsapps* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsSoundRecorder* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsStore* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Xbox.TCUI* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxApp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxGameOverlay* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxIdentityProvider* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxSpeechToTextOverlay* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxSpeechToTextOverlay* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.ZuneMusic* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.ZuneVideo* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.BingNews* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.GamingApp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Clipchamp.Clipchamp* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.PowerAutomateDesktop* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.Todos* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.WindowsMaps* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *Microsoft.XboxGamingOverlay* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *MicrosoftCorporationII.QuickAssist* | Remove-AppxProvisionedPackage -online"
powershell "Get-AppxProvisionedPackage -online | Where PackageName -like *MicrosoftTeams* | Remove-AppxProvisionedPackage -online"
powershell "Get-WindowsPackage -Online | Where PackageName -like *QuickAssist* | Remove-WindowsPackage -Online -NoRestart"
powershell "Get-WindowsPackage -Online | Where PackageName -like *Hello-Face* | Remove-WindowsPackage -Online -NoRestart"
powershell "Get-WindowsOptionalFeature -Online | Where FeatureName -eq *WindowsMediaPlayer* | Disable-WindowsOptionalFeature -Online -NoRestart -WarningAction SilentlyContinue | Out-Null"
powershell "Get-WindowsOptionalFeature -Online | Where FeatureName -eq *WorkFolders-Client* | Disable-WindowsOptionalFeature -Online -NoRestart -WarningAction SilentlyContinue | Out-Null"
powershell "Get-WindowsOptionalFeature -Online | Where FeatureName -eq *Printing-XPSServices-Features* | Disable-WindowsOptionalFeature -Online -NoRestart -WarningAction SilentlyContinue | Out-Null"
powershell "Get-WindowsOptionalFeature -Online | Where FeatureName -eq *FaxServicesClientPackage* | Disable-WindowsOptionalFeature -Online -NoRestart -WarningAction SilentlyContinue | Out-Null"
powershell "Remove-Printer -Name "Fax" -ErrorAction SilentlyContinue"
powershell "Get-WindowsCapability -Online | Where Name -like *Media.WindowsMediaPlayer* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *MathRecognizer* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *Hello.Face* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *OpenSSH.Client* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *OpenSSH.Server* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *Print.Fax.Scan* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *Print.Management.Console* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *Microsoft.Windows.WordPad* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *App.StepsRecorder* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *OneCoreUAP.OneSync* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-WindowsCapability -Online | Where Name -like *Microsoft.Windows.PowerShell.ISE* | Remove-WindowsCapability -Online | Out-Null"
powershell "Get-AppPackage -Allusers *MicrosoftWindows.Client.CBS* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Windows.SecureAssessmentBrowser* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.CredDialogHost* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Windows.ParentalControls* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.XboxGameCallableUI* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.MicrosoftEdgeDevToolsClient* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Windows.PeopleExperienceHost* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Windows.NarratorQuickStart* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Win32WebViewHost* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.Windows.XGpuEjectDialog* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Windows.PrintDialog* | Remove-AppPackage"
powershell "Get-AppPackage -Allusers *Microsoft.MicrosoftEdge* | Remove-AppPackage"
DISM /Online /Remove-ProvisionedAppxPackage /PackageName:Microsoft.XboxGamingOverlay_2.34.28001.0_neutral_~_8wekyb3d8bbwe
DISM /Online /Remove-ProvisionedAppxPackage /PackageName:Microsoft.WindowsMaps_2019.716.2316.0_neutral_~_8wekyb3d8bbwe

